= Initial setup

. Install Linux to a provided computer.
Use the provided USB stick.
You should choose the simple install and overwrite any existing OS-es.
.. Use `robot` for both the username and password.
. Install `distutils` for python :
+
[source,bash]
----
sudo apt-get install python3-distutils
----
. Install a IDE of your choice.
Visual Studio Code or PyCharm are good options.
Visual Studio Code can be simply installed from the Ubuntu Software app.
Later you might want to install python specific plugins for the IDE as well.
. Install git.
. Use Git to clone the provided example repository to a directory of your choice: +
*https://github.com/ut-robotics/picr22-boot-camp-programming*
. Install the required dependencies using pip:
+
[source,bash]
----
pip install opencv-python pyrealsense2 numpy
----
. Familiarise yourself with the provided README file.
. Compile the segmentation library as by the instructions.
Remember that you need python dev tools to compile code (python3-dev and build-essential).
. Connect a camera and try running the `config_colors.py` and `main.py` files.
Both programs can be quit out of by pressing `q` when a camera window is active.
. If they work, you can continue to the next step.
In case of issues, consult with instructors.
