= Team documentation requirements

== Introduction

By the end of this course, each team must have a documentation that has the required data described in it.
This will give future students and other robot builders access to previous years knowledge
and experience on robot building to improve overall quality of their robots.

== Documentation requirements

=== Team repository structure

* *README.asciidoc*
** Names of all team members.
** Links to all external sources (public link to Fusion 360 assembly and any other repositories).
** Programming section (see below for requirements).
** Electronics section (see below for requirements).
** Mechanics section (see below for requirements).
** Personal comments section (see below for requirements).
** Blogs at the end.
* *software/README.asciidoc*
** Instructions on how to set up and run the code.
* *electronics/README.asciidoc*
** Refer to "Mainboard documented" task requirements.
* *firmware/README.asciidoc*
** Format and description of the data that can be sent to and received from mainboard.

=== README.asciidoc sections

==== Programming

The following questions must be answered:

* What libraries did you use (and for what purposes)?
* A brief description of your game logic and overall code structure.
* A block diagram of your game logic.
* A short analysis of what was good and bad in your code and how to improve.

==== Electronics

* If you used something different from what was given at the start of the course
or did something different, describe it.
* Photos illustrating electronics on your robot. (electronics board, cable management, etc.)
* A short analysis of what was good and bad in your electronics and how to improve.

==== Mechanics

* If you used something different from what was given at the start of the course
or did something different, describe it.
* Description of the main points of interest in your ball thrower design and construction process.
* Photos of your robot.
* A short analysis of what was good and bad in your mechanics and how to improve.

==== Personal comments

Each member must write a paragraph that covers the following:

* On which parts of the robot did you work on?
* What did you learn?
* What would you do differently next time?
* What did you like/did not like about the course/building a robot?
* Suggestions for next year students.
* Suggestions for instructors.
